//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescuePets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoption
    {
        public int AdoptionID { get; set; }
        public int PetID { get; set; }
        public int AdopterUserID { get; set; }
        public System.DateTime AdoptionDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
