//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescuePets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.Adoptions = new HashSet<Adoption>();
        }
    
        public int PetID { get; set; }
        public string PetName { get; set; }
        public int TypeID { get; set; }
        public int BreedID { get; set; }
        public int LocationID { get; set; }
        public int Age { get; set; }
        public decimal Weight { get; set; }
        public int GenderID { get; set; }
        public string PetStory { get; set; }
        public string ImageData { get; set; }
        public string Status { get; set; }
        public int PostedByUserID { get; set; }
        public System.DateTime DatePosted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Location Location { get; set; }
        public virtual PetBreed PetBreed { get; set; }
        public virtual User User { get; set; }
        public virtual PetType PetType { get; set; }
    }
}
